apiVersion: v1
kind: Service
metadata:
  name: wilsonchai-webhook-svc
spec:
  ports:
  - port: 443
    targetPort: 443

---

apiVersion: v1
kind: Endpoints
metadata:
  name: wilsonchai-webhook-svc
subsets:
- addresses:
  - ip: 10.248.33.220
  ports:
    - port: 443