apiVersion: v1
kind: ServiceAccount
metadata:
  name: wilsonchai-webhook-sa
  labels:
    app: wilsonchai-webhook

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: wilsonchai-webhook-cr
  labels:
    app: wilsonchai-webhook
rules:
- apiGroups:
  - wilsonchai.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - events
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - autoscaling
  resources:
  - '*'
  verbs:
  - '*'

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wilsonchai-webhook-crb 
  labels:
    app: wilsonchai-webhook
subjects:
- kind: ServiceAccount
  name: wilsonchai-webhook-sa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: wilsonchai-webhook-cr
